@startuml

package butterfly #DDDDDD
{

class ArgumentParser
{
    - _argc: int
    - _argv: char**
    - _args: std::vector

    - showUsage() const: void
    - showVersion() const: void

    + ArgumentParser(int argc, char *argv[])

    + parseArgs(): ArgumentParser::Arguments
}

}
@enduml