@startuml
'https://plantuml.com/sequence-diagram
class CryptoRSA {
    String test
    void initPaddingSize()
}

class RSAEncryptor {
}
class RSADecryptor {
}

CryptoRSA <-- RSAEncryptor
CryptoRSA <-- RSADecryptor
@enduml