@startuml
participant Encryptor
participant rsaEncryptorAESKey
participant rsaEncryptorCPrivateRSA

Encryptor -> rsaEncryptorAESKey: Encrypt AES Key String
Encryptor <- rsaEncryptorAESKey: AESKey.bin
Encryptor -> rsaEncryptorCPrivateRSA: Encrypt RSA Private Key String
Encryptor <- rsaEncryptorCPrivateRSA: CPrivateRSA.bin

@enduml

