@startuml

actor target
actor attacker

component Butterfly  as "                    Butterfly" {

component Encryption
component Decryption

component Payment
component Visualization
component HTTP
component TorProxy

portout Ext

attacker -u-> Encryption
Encryption -u-> HTTP

target -d-> Payment
Payment -d-> HTTP

HTTP -> TorProxy

HTTP -l-> Visualization

HTTP -d-> Decryption
}

component TorHiddenService
component Webserver

TorProxy -r- Ext
Ext -r0)- TorHiddenService

TorHiddenService -d-> Webserver

@enduml