@startuml

actor target
actor attacker

component Butterfly {

component Encryption
component Decryption

component Payment
component Visualization
component Webserver

component TorProxy
component TorHiddenService

attacker -u-> Encryption
Encryption -u-> Visualization

target -d-> Payment
Payment -d-> Visualization

Visualization -> TorProxy
TorProxy -> TorHiddenService
TorHiddenService -> Webserver

Webserver -d-> Decryption

}
@enduml