@startuml

actor target
actor attacker

component Encryption
component Decryption

component Payment
component Visualization
component Webserver

component TorProxy
component TorHiddenService

attacker -> Encryption
Encryption -u-> Visualization

target -> Payment
Payment -d-> Visualization

Visualization -> TorProxy
TorProxy -> TorHiddenService
TorHiddenService -> Webserver
Webserver -d-> Decryption

@enduml