@startuml
'https://plantuml.com/sequence-diagram
package AES #DDDDDD
{

class CryptoAES
{
}

class AESEncryptor
{

}

class AESDecryptor
{

}

CryptoAES <-- AESEncryptor
CryptoAES <-- AESDecryptor
}
@enduml