@startuml

package butterfly #AAAAAA
{

package aes #DDDDDD
{

class CryptoAES
{
    - _aesEncryptContext, _aesDecryptContext: EVP_CIPHER_CTX*
    - _aesKeyLength, _aesIvLength, _aesSaltLength: int

    # {static} aesKey, aesIv: unsigned char*

    - {static} getOpenSSLError(): std::string

    + CryptoAES()

    + {static} isInitialized(): bool
    + generateAESKey() const: bool
    + generateAESKeyWithSalt() const: bool

    + setAESKey(std::string &aesKey): void
    + setAESIv(std::string &aesIv): void
    + getAESKey() const: std::string
    + getAESIv() const: std::string
    + getAESKeyPair() const: std::string
    + getAESKeyLength() const: int
    + getAESIVLength() const: int

    + encrypt(const unsigned char *plaintext, size_t plaintextLength, unsigned char **ciphertext): size_t
    + decrypt(unsigned char *ciphertext, size_t ciphertextLength, unsigned char **plaintext): size_t
    + encrypt(std::ifstream &fin, std::ofstream &fout): size_t
    + decrypt(std::ifstream &fin, std::ofstream &fout): size_t
}

}

}

@enduml