@startuml
'https://plantuml.com/class-diagram

package butterfly #AAAAAA
{

package hybrid #DDDDDD
{

class CryptoProcess
{
    - _processIds: std::vector<pid_t>
    - handleLargeFilesWithAES(const std::string &filepath) = 0: void

    + CryptoProcess()

    + create(): void
    + waitAll(): void
}

}

}

@enduml