@startuml
'https://plantuml.com/class-diagram

package butterfly #AAAAAA
{

package hybrid #DDDDDD
{

class CryptoSecurity
{

    + CryptoSecurity()

    + {static} saveUnencryptedAESKeyPair(const std::string &aesKeyPair): void
    + {static} areEncryptionFilesAvailable(): bool
    + {static} removeDecryptedFiles(): void
    + {static} getAESKeyPairFromUnencryptedFile(std::string &aesKeyPair): bool
}

}

}

@enduml