@startuml
'https://plantuml.com/sequence-diagram

package butterfly #AAAAAA
{

package hybrid #DDDDDD
{

class Encryptor
{
    - _keySize: Int
    - _rsaEncryptorCPrivateRSA: RSAEncryptor
    - _rsaEncryptorAESKey: RSAEncryptor
}

class Decryptor
{

    -_rsaDecryptorAESKey: RSADecryptor
    -_rsaDecryptorCPrivateRSA: RSADecryptor
}

}

}
@enduml