@startuml

package butterfly #AAAAAA
{

package rsa #DDDDDD
{

class CryptoRSA
{
    - _pkey: EVP_PKEY*
    - _keySize, _paddingSize: int
    - _rsaPrivateKeyStr, _privateKeyStr, _publicKeyStr: char*
    - _encryptedKey, _iv: unsigned char*
    - rsaEncryptContext, rsaDecryptContext: EVP_CIPHER_CTX*

    - getOpenSSLError(): string
    - generateRSAKey(): bool
    - loadKeyFromFile(const std::string &filepath): void
    - loadKeyFromStr(const std::string &str): void
    - validateStringLengthForRSA(const std::string &msg, const int &keysize): bool

    # getPaddingSize(): int

    + CryptoRSA(int keySize)
    + CryptoRSA(const std::string &key)

    + getRSAIV() const: unsigned char*
    + getRSAEncryptedKey() const: unsigned char*
    + getEvpPkey(): EVP_PKEY*
    + getEvpPkeySize(EVP_PKEY *key): int

    + getRSAPrivateKeyStr(): char*
    + getPrivateKeyStr(): char*
    + getPublicKeyStr(): char*

    + encrpytEVP(EVP_PKEY *key, const unsigned char *plaintext, size_t plaintextLength, unsigned char **ciphertext): int
    + decryptEVP(EVP_PKEY *key, unsigned char *ciphertext, size_t ciphertextLength, unsigned char *encryptedKey, unsigned char *iv, unsigned char **plaintext): int
    + encrypt(EVP_PKEY *key, const unsigned char *plaintext, size_t plaintextLength, unsigned char *ciphertext): int
    + decrypt(EVP_PKEY *key, unsigned char* ciphertext, size_t ciphertextLength, unsigned char* plaintext): int
}

class RSAEncryptor
{
    - _encryptedMessage: std::string

    - validateStringLengthForRSA(const std::string &msg, const int &keysize): bool
    - writeRSAFileToSystem(const RSAKEY_TYPE &type): bool

    + RSAEncryptor(int keySize)
    + RSAEncryptor(const std::string &key)

    + getEncryptedMessage() const: std::string
    + writeEncMSGToFile(const std::string &filename, const std::string &ciphertextMsg, int ciphertextMsgLength): void

    + encrypt(EVP_PKEY *pkey, const std::string &decMSG): int
    + encryptEVP(EVP_PKEY *pkey, const std::string &decMSG, const RSAKEY_TYPE &type): int
}

class RSADecryptor
{
    - _decryptedMessage: std::string
    - validateStringLengthForRSA(const std::string &msg, const int &keysize): bool
    - readRSAFileFromSystem(const RSAKEY_TYPE &rsakeysType, std::string &encKey, std::string &iv): void

    + RSADecryptor() = delete
    + RSADecryptor(const std::string &key)

    + getDecryptedMessage(): std::string
    + readEncMSGFromFile(const std::string &filepath): std::string

    + decrypt(EVP_PKEY *pkey, const std::string &encMSG): int
    + decryptEVP(EVP_PKEY *pkey, const std::string &encMSG, std::string &decMSG, const RSAKEY_TYPE &type): int
}

CryptoRSA <|-- RSAEncryptor
CryptoRSA <|-- RSADecryptor

}

}
@enduml