@startuml
'https://plantuml.com/sequence-diagram

actor attacker
participant SPrivateRSA.pem as SPrivate
actor target
participant "SPublic.pem\n(embedded)" as SPublic
participant CPrivateRSA.pem as CPrivate
participant CPublic.pem as CPublic
participant "AESKey/AESIv" as AESKey
participant File
'participant AESKeySQL.sql as AESKeySQL

autonumber
hnote over SPrivate, SPublic: server rsa key pair (keysize: 13768)
hnote over CPrivate, CPublic: client rsa key pair (keysize: 2048)
hnote over AESKey: 256-Bit-AESKey/128-Bit-AESIv
...
attacker <- target: target pays ransom
attacker -> target: attacker sends the **SPrivateRSA.pem** file

target -> CPrivate: decrypt the **CPrivateRSA.bin**\n with **SPrivateRSA.pem**
CPrivate -> target: get the decrypted **CPrivateRSA.pem**
note left: **CPrivateRSA.pem**
target -> AESKey: decrypt the **AESKey.bin & AESIV.bin** with **CPrivateRSA.pem**
note right: **AESKey & AESIV**

loop
File <- AESKey: get file with butterfly ending
File -> AESKey: decrypt ***.bfly** file with **AESKey&AESIV**
File <- AESKey: get original file
note right: **~*.txt**
end
File -> target: target has again access to all user files

@enduml